/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ACCENT_COLORS: typeof import('./stores/settings/index').ACCENT_COLORS
  const AI_PROVIDER_PRESETS: typeof import('./lib/ai-provider/index').AI_PROVIDER_PRESETS
  const AUTO_CLOSE_INACTIVE_TABS_HOURS_DEFAULT: typeof import('./stores/settings/index').AUTO_CLOSE_INACTIVE_TABS_HOURS_DEFAULT
  const AUTO_CLOSE_INACTIVE_TABS_HOURS_MAX: typeof import('./stores/settings/index').AUTO_CLOSE_INACTIVE_TABS_HOURS_MAX
  const AUTO_CLOSE_INACTIVE_TABS_HOURS_MIN: typeof import('./stores/settings/index').AUTO_CLOSE_INACTIVE_TABS_HOURS_MIN
  const Activity: typeof import('react').Activity
  const AiGradientIcon: typeof import('./components/ui/ai-gradient-icon').AiGradientIcon
  const BEAM_MIN_ACTIVE_MS: typeof import('./components/ui/ai-motion').BEAM_MIN_ACTIVE_MS
  const Badge: typeof import('./components/ui/badge').Badge
  const Button: typeof import('./components/ui/button').Button
  const CARD_THEMES: typeof import('./lib/imageExport/index').CARD_THEMES
  const CONVERSATION_STALE_MS: typeof import('./stores/useNotebookAiChats').CONVERSATION_STALE_MS
  const Card: typeof import('./components/ui/card').Card
  const CardContent: typeof import('./components/ui/card').CardContent
  const CardDescription: typeof import('./components/ui/card').CardDescription
  const CardFooter: typeof import('./components/ui/card').CardFooter
  const CardHeader: typeof import('./components/ui/card').CardHeader
  const CardTitle: typeof import('./components/ui/card').CardTitle
  const Command: typeof import('./components/ui/command').Command
  const CommandDialog: typeof import('./components/ui/command').CommandDialog
  const CommandEmpty: typeof import('./components/ui/command').CommandEmpty
  const CommandGroup: typeof import('./components/ui/command').CommandGroup
  const CommandInput: typeof import('./components/ui/command').CommandInput
  const CommandItem: typeof import('./components/ui/command').CommandItem
  const CommandList: typeof import('./components/ui/command').CommandList
  const ContextMenu: typeof import('./components/ui/context-menu').ContextMenu
  const ContextMenuCheckboxItem: typeof import('./components/ui/context-menu').ContextMenuCheckboxItem
  const ContextMenuContent: typeof import('./components/ui/context-menu').ContextMenuContent
  const ContextMenuGroup: typeof import('./components/ui/context-menu').ContextMenuGroup
  const ContextMenuItem: typeof import('./components/ui/context-menu').ContextMenuItem
  const ContextMenuLabel: typeof import('./components/ui/context-menu').ContextMenuLabel
  const ContextMenuPortal: typeof import('./components/ui/context-menu').ContextMenuPortal
  const ContextMenuRadioGroup: typeof import('./components/ui/context-menu').ContextMenuRadioGroup
  const ContextMenuRadioItem: typeof import('./components/ui/context-menu').ContextMenuRadioItem
  const ContextMenuSeparator: typeof import('./components/ui/context-menu').ContextMenuSeparator
  const ContextMenuShortcut: typeof import('./components/ui/context-menu').ContextMenuShortcut
  const ContextMenuSub: typeof import('./components/ui/context-menu').ContextMenuSub
  const ContextMenuSubContent: typeof import('./components/ui/context-menu').ContextMenuSubContent
  const ContextMenuSubTrigger: typeof import('./components/ui/context-menu').ContextMenuSubTrigger
  const ContextMenuTrigger: typeof import('./components/ui/context-menu').ContextMenuTrigger
  const DEEPSEEK_BASE_URL: typeof import('./lib/ai-provider/index').DEEPSEEK_BASE_URL
  const DEFAULT_ACCENT_COLOR: typeof import('./stores/settings/index').DEFAULT_ACCENT_COLOR
  const DEFAULT_APP_SHORTCUTS: typeof import('./stores/settings/index').DEFAULT_APP_SHORTCUTS
  const DEFAULT_CLAUDE_BASE_URL: typeof import('./lib/ai-provider/index').DEFAULT_CLAUDE_BASE_URL
  const DEFAULT_CLOSE_TAB_SHORTCUT: typeof import('./stores/settings/index').DEFAULT_CLOSE_TAB_SHORTCUT
  const DEFAULT_FONT_NAMES: typeof import('./lib/fontLoader').DEFAULT_FONT_NAMES
  const DEFAULT_NOTEBOOK: typeof import('./stores/useNotebooks').DEFAULT_NOTEBOOK
  const DEFAULT_OPENAI_BASE_URL: typeof import('./lib/ai-provider/index').DEFAULT_OPENAI_BASE_URL
  const DEFAULT_QUICKNOTE_HOTKEY: typeof import('./stores/settings/index').DEFAULT_QUICKNOTE_HOTKEY
  const DEFAULT_SEARCH_HOTKEY: typeof import('./stores/settings/index').DEFAULT_SEARCH_HOTKEY
  const DEFAULT_SEARCH_PANEL_CLOSE_SHORTCUT: typeof import('./stores/settings/index').DEFAULT_SEARCH_PANEL_CLOSE_SHORTCUT
  const DEFAULT_SEARCH_PROVIDERS: typeof import('./stores/settings/index').DEFAULT_SEARCH_PROVIDERS
  const DEFAULT_WAKE_HOTKEY: typeof import('./stores/settings/index').DEFAULT_WAKE_HOTKEY
  const DEFAULT_WATERMARK_CONFIG: typeof import('./lib/imageExport/index').DEFAULT_WATERMARK_CONFIG
  const Dialog: typeof import('./components/ui/dialog').Dialog
  const DialogClose: typeof import('./components/ui/dialog').DialogClose
  const DialogContent: typeof import('./components/ui/dialog').DialogContent
  const DialogDescription: typeof import('./components/ui/dialog').DialogDescription
  const DialogFooter: typeof import('./components/ui/dialog').DialogFooter
  const DialogHeader: typeof import('./components/ui/dialog').DialogHeader
  const DialogOverlay: typeof import('./components/ui/dialog').DialogOverlay
  const DialogPortal: typeof import('./components/ui/dialog').DialogPortal
  const DialogShell: typeof import('./components/ui/dialog-shell').DialogShell
  const DialogTitle: typeof import('./components/ui/dialog').DialogTitle
  const DialogTrigger: typeof import('./components/ui/dialog').DialogTrigger
  const DiskWriteError: typeof import('./lib/diskWriteError').DiskWriteError
  const DropdownMenu: typeof import('./components/ui/dropdown-menu').DropdownMenu
  const DropdownMenuCheckboxItem: typeof import('./components/ui/dropdown-menu').DropdownMenuCheckboxItem
  const DropdownMenuContent: typeof import('./components/ui/dropdown-menu').DropdownMenuContent
  const DropdownMenuGroup: typeof import('./components/ui/dropdown-menu').DropdownMenuGroup
  const DropdownMenuItem: typeof import('./components/ui/dropdown-menu').DropdownMenuItem
  const DropdownMenuLabel: typeof import('./components/ui/dropdown-menu').DropdownMenuLabel
  const DropdownMenuPortal: typeof import('./components/ui/dropdown-menu').DropdownMenuPortal
  const DropdownMenuRadioGroup: typeof import('./components/ui/dropdown-menu').DropdownMenuRadioGroup
  const DropdownMenuRadioItem: typeof import('./components/ui/dropdown-menu').DropdownMenuRadioItem
  const DropdownMenuSeparator: typeof import('./components/ui/dropdown-menu').DropdownMenuSeparator
  const DropdownMenuShortcut: typeof import('./components/ui/dropdown-menu').DropdownMenuShortcut
  const DropdownMenuSub: typeof import('./components/ui/dropdown-menu').DropdownMenuSub
  const DropdownMenuSubContent: typeof import('./components/ui/dropdown-menu').DropdownMenuSubContent
  const DropdownMenuSubTrigger: typeof import('./components/ui/dropdown-menu').DropdownMenuSubTrigger
  const DropdownMenuTrigger: typeof import('./components/ui/dropdown-menu').DropdownMenuTrigger
  const EDITOR_CONTEXT_UI_GAP: typeof import('./components/editor/utils/editorContextUi').EDITOR_CONTEXT_UI_GAP
  const EDITOR_FONT_SIZE_DEFAULT: typeof import('./stores/settings/index').EDITOR_FONT_SIZE_DEFAULT
  const EDITOR_FONT_SIZE_MAX: typeof import('./stores/settings/index').EDITOR_FONT_SIZE_MAX
  const EDITOR_FONT_SIZE_MIN: typeof import('./stores/settings/index').EDITOR_FONT_SIZE_MIN
  const EDITOR_ONLY_FIXED_SHORTCUTS: typeof import('./lib/shortcut-platform').EDITOR_ONLY_FIXED_SHORTCUTS
  const EDITOR_SPLIT_PERSIST_KEY_PREFIX: typeof import('./stores/useEditorSplit').EDITOR_SPLIT_PERSIST_KEY_PREFIX
  const EDITOR_UI_SCALE_CHANGE_EVENT: typeof import('./lib/appearance').EDITOR_UI_SCALE_CHANGE_EVENT
  const ELECTRON_MAX_FILE_ATTACHMENT_SIZE: typeof import('./lib/fileStorage').ELECTRON_MAX_FILE_ATTACHMENT_SIZE
  const ELECTRON_MAX_VIDEO_ATTACHMENT_SIZE: typeof import('./lib/videoStorage').ELECTRON_MAX_VIDEO_ATTACHMENT_SIZE
  const FILE_NAV_AI_PANEL: typeof import('./stores/useFileNavHistory').FILE_NAV_AI_PANEL
  const FILE_NAV_WELCOME: typeof import('./stores/useFileNavHistory').FILE_NAV_WELCOME
  const FIXED_APP_SHORTCUT_IDS: typeof import('./lib/fixed-app-shortcuts').FIXED_APP_SHORTCUT_IDS
  const FeatureToastCard: typeof import('./components/ui/feature-toast-card').FeatureToastCard
  const Fragment: typeof import('react').Fragment
  const GLM_BASE_URL: typeof import('./lib/ai-provider/index').GLM_BASE_URL
  const GOOSE_FAVORITE_KEY: typeof import('./lib/local-frontmatter').GOOSE_FAVORITE_KEY
  const GOOSE_FONT_KEY: typeof import('./lib/local-frontmatter').GOOSE_FONT_KEY
  const GOOSE_LOCKED_KEY: typeof import('./lib/local-frontmatter').GOOSE_LOCKED_KEY
  const GOOSE_PINNED_KEY: typeof import('./lib/local-frontmatter').GOOSE_PINNED_KEY
  const IMAGE_EXPORT_LIVE_PREVIEW_MIN_WIDTH: typeof import('./lib/imageExport/index').IMAGE_EXPORT_LIVE_PREVIEW_MIN_WIDTH
  const IMAGE_EXPORT_OPTIONS_CORNER_MIN_WIDTH: typeof import('./lib/imageExport/index').IMAGE_EXPORT_OPTIONS_CORNER_MIN_WIDTH
  const INTERNAL_ASSET_REF_PREFIXES: typeof import('./lib/internalAssetRef').INTERNAL_ASSET_REF_PREFIXES
  const IconButton: typeof import('./components/ui/icon-button').IconButton
  const ImageExportThemeSelector: typeof import('./components/ui/image-export-theme-selector').ImageExportThemeSelector
  const Input: typeof import('./components/ui/input').Input
  const Kbd: typeof import('./components/ui/kbd').Kbd
  const LEGACY_BLOCK_TYPES: typeof import('./components/editor/utils/blocknote-content/index').LEGACY_BLOCK_TYPES
  const LIST_PASTE_BLOCK_TYPES: typeof import('./components/editor/utils/multilinePaste').LIST_PASTE_BLOCK_TYPES
  const LOCAL_FOLDER_EDITOR_CANDIDATES: typeof import('./lib/local-folder-open-apps').LOCAL_FOLDER_EDITOR_CANDIDATES
  const LOCAL_FOLDER_FILE_MANAGER_CANDIDATES: typeof import('./lib/local-folder-open-apps').LOCAL_FOLDER_FILE_MANAGER_CANDIDATES
  const LOCAL_FOLDER_TERMINAL_CANDIDATES: typeof import('./lib/local-folder-open-apps').LOCAL_FOLDER_TERMINAL_CANDIDATES
  const LOCAL_PAGE_FRONTMATTER_SETTINGS_KEYS: typeof import('./lib/local-frontmatter').LOCAL_PAGE_FRONTMATTER_SETTINGS_KEYS
  const Label: typeof import('./components/ui/label').Label
  const LucideIcons: typeof import('lucide-react')
  const MAX_FILE_ATTACHMENT_SIZE: typeof import('./lib/fileStorage').MAX_FILE_ATTACHMENT_SIZE
  const MAX_VIDEO_ATTACHMENT_SIZE: typeof import('./lib/videoStorage').MAX_VIDEO_ATTACHMENT_SIZE
  const MINIMAX_BASE_URL: typeof import('./lib/ai-provider/index').MINIMAX_BASE_URL
  const NON_CUSTOMIZABLE_APP_SHORTCUT_IDS: typeof import('./lib/fixed-app-shortcuts').NON_CUSTOMIZABLE_APP_SHORTCUT_IDS
  const NOTEBOOK_AI_TAB_PAGE_ID_PREFIX: typeof import('./stores/useTabs').NOTEBOOK_AI_TAB_PAGE_ID_PREFIX
  const NOTEBOOK_THEME: typeof import('./lib/imageExport/index').NOTEBOOK_THEME
  const ONBOARDING_CHILD_PAGE_CONTENT: typeof import('./lib/onboarding').ONBOARDING_CHILD_PAGE_CONTENT
  const ONBOARDING_PAGE_CONTENT: typeof import('./lib/onboarding').ONBOARDING_PAGE_CONTENT
  const ONBOARDING_SECOND_CHILD_CONTENT: typeof import('./lib/onboarding').ONBOARDING_SECOND_CHILD_CONTENT
  const ONBOARDING_THIRD_CHILD_CONTENT: typeof import('./lib/onboarding').ONBOARDING_THIRD_CHILD_CONTENT
  const ORB_PHASE_HOLD_MS: typeof import('./components/ui/ai-motion').ORB_PHASE_HOLD_MS
  const ORB_VISIBLE_MIN_MS: typeof import('./components/ui/ai-motion').ORB_VISIBLE_MIN_MS
  const Popover: typeof import('./components/ui/popover').Popover
  const PopoverAction: typeof import('./components/ui/popover').PopoverAction
  const PopoverAnchor: typeof import('./components/ui/popover').PopoverAnchor
  const PopoverContent: typeof import('./components/ui/popover').PopoverContent
  const PopoverTrigger: typeof import('./components/ui/popover').PopoverTrigger
  const Portal: typeof import('./components/ui/portal').Portal
  const Progress: typeof import('./components/ui/progress').Progress
  const QUICKNOTE_DEFAULT_HEIGHT: typeof import('./stores/useQuickNote').QUICKNOTE_DEFAULT_HEIGHT
  const QUICKNOTE_DEFAULT_WIDTH: typeof import('./stores/useQuickNote').QUICKNOTE_DEFAULT_WIDTH
  const QUICKNOTE_MIN_HEIGHT: typeof import('./stores/useQuickNote').QUICKNOTE_MIN_HEIGHT
  const QUICKNOTE_MIN_WIDTH: typeof import('./stores/useQuickNote').QUICKNOTE_MIN_WIDTH
  const QUICKNOTE_SLOTS: typeof import('./stores/useQuickNote').QUICKNOTE_SLOTS
  const QUICKNOTE_SLOT_COUNT: typeof import('./stores/useQuickNote').QUICKNOTE_SLOT_COUNT
  const QUICKNOTE_ZOOM_DEFAULT: typeof import('./stores/useQuickNote').QUICKNOTE_ZOOM_DEFAULT
  const QUICKNOTE_ZOOM_MAX: typeof import('./stores/useQuickNote').QUICKNOTE_ZOOM_MAX
  const QUICKNOTE_ZOOM_MIN: typeof import('./stores/useQuickNote').QUICKNOTE_ZOOM_MIN
  const QUICKNOTE_ZOOM_STEP: typeof import('./stores/useQuickNote').QUICKNOTE_ZOOM_STEP
  const REMOTE_FONT_SOURCES: typeof import('./lib/fontLoader').REMOTE_FONT_SOURCES
  const REMOVED_APP_SHORTCUT_IDS: typeof import('./lib/fixed-app-shortcuts').REMOVED_APP_SHORTCUT_IDS
  const SIDEBAR_FONT_SIZE_DEFAULT: typeof import('./stores/settings/index').SIDEBAR_FONT_SIZE_DEFAULT
  const SIDEBAR_FONT_SIZE_MAX: typeof import('./stores/settings/index').SIDEBAR_FONT_SIZE_MAX
  const SIDEBAR_FONT_SIZE_MIN: typeof import('./stores/settings/index').SIDEBAR_FONT_SIZE_MIN
  const ScrollArea: typeof import('./components/ui/scroll-area').ScrollArea
  const ScrollBar: typeof import('./components/ui/scroll-area').ScrollBar
  const SelectableCard: typeof import('./components/ui/selectable-card').SelectableCard
  const Separator: typeof import('./components/ui/separator').Separator
  const Sheet: typeof import('./components/ui/sheet').Sheet
  const SheetClose: typeof import('./components/ui/sheet').SheetClose
  const SheetContent: typeof import('./components/ui/sheet').SheetContent
  const SheetDescription: typeof import('./components/ui/sheet').SheetDescription
  const SheetFooter: typeof import('./components/ui/sheet').SheetFooter
  const SheetHeader: typeof import('./components/ui/sheet').SheetHeader
  const SheetOverlay: typeof import('./components/ui/sheet').SheetOverlay
  const SheetPortal: typeof import('./components/ui/sheet').SheetPortal
  const SheetTitle: typeof import('./components/ui/sheet').SheetTitle
  const SheetTrigger: typeof import('./components/ui/sheet').SheetTrigger
  const Slider: typeof import('./components/ui/slider').Slider
  const Suspense: typeof import('react').Suspense
  const Switch: typeof import('./components/ui/switch').Switch
  const THINKING_PLACEHOLDER_MIN_MS: typeof import('./components/ui/ai-motion').THINKING_PLACEHOLDER_MIN_MS
  const TIPS: typeof import('./lib/tips').TIPS
  const TITLE_HEADING_LEVEL: typeof import('./components/editor/utils/blocknote-content/index').TITLE_HEADING_LEVEL
  const TOOLTIP_DELAY_MS: typeof import('./components/ui/tooltip-delay').TOOLTIP_DELAY_MS
  const Table: typeof import('./components/ui/table').Table
  const TableBody: typeof import('./components/ui/table').TableBody
  const TableCaption: typeof import('./components/ui/table').TableCaption
  const TableCell: typeof import('./components/ui/table').TableCell
  const TableFooter: typeof import('./components/ui/table').TableFooter
  const TableHead: typeof import('./components/ui/table').TableHead
  const TableHeader: typeof import('./components/ui/table').TableHeader
  const TableRow: typeof import('./components/ui/table').TableRow
  const Tabs: typeof import('./components/ui/tabs').Tabs
  const TabsContent: typeof import('./components/ui/tabs').TabsContent
  const TabsList: typeof import('./components/ui/tabs').TabsList
  const TabsTrigger: typeof import('./components/ui/tabs').TabsTrigger
  const Textarea: typeof import('./components/ui/textarea').Textarea
  const Toaster: typeof import('./components/ui/sonner').Toaster
  const Toggle: typeof import('./components/ui/toggle').Toggle
  const Tooltip: typeof import('./components/ui/tooltip').Tooltip
  const TooltipContent: typeof import('./components/ui/tooltip').TooltipContent
  const TooltipProvider: typeof import('./components/ui/tooltip').TooltipProvider
  const TooltipTrigger: typeof import('./components/ui/tooltip').TooltipTrigger
  const TriggerChild: typeof import('./components/ui/trigger-child').TriggerChild
  const UI_FONT_SIZE_MAP: typeof import('./lib/appearance').UI_FONT_SIZE_MAP
  const UNTITLED_PAGE_TITLE: typeof import('./components/editor/utils/page-title').UNTITLED_PAGE_TITLE
  const UTOOLS_WINDOW_HEIGHT_DEFAULT: typeof import('./stores/settings/index').UTOOLS_WINDOW_HEIGHT_DEFAULT
  const UTOOLS_WINDOW_HEIGHT_MAX: typeof import('./stores/settings/index').UTOOLS_WINDOW_HEIGHT_MAX
  const UTOOLS_WINDOW_HEIGHT_MIN: typeof import('./stores/settings/index').UTOOLS_WINDOW_HEIGHT_MIN
  const UToolsAdapter: typeof import('./lib/utools').UToolsAdapter
  const VALID_BLOCK_TYPES: typeof import('./components/editor/utils/blocknote-content/index').VALID_BLOCK_TYPES
  const VIDEO_OUTPUT_MIME: typeof import('./lib/videoProcessor').VIDEO_OUTPUT_MIME
  const WELCOME_TAB_PAGE_ID: typeof import('./stores/useTabs').WELCOME_TAB_PAGE_ID
  const activateNotebook: typeof import('./lib/notebookNavigation').activateNotebook
  const applyAccentColor: typeof import('./lib/accentColor').applyAccentColor
  const applyAppearanceScaleVariables: typeof import('./lib/appearance').applyAppearanceScaleVariables
  const applyBlockTypeTransformToContiguousIds: typeof import('./lib/ai-write/index').applyBlockTypeTransformToContiguousIds
  const applyBlockTypeTransformToEditor: typeof import('./lib/ai-write/index').applyBlockTypeTransformToEditor
  const applyFontVariables: typeof import('./lib/fontLoader').applyFontVariables
  const applyFrontmatterBodyToContent: typeof import('./lib/local-frontmatter').applyFrontmatterBodyToContent
  const applyPersistedTabSplit: typeof import('./stores/useEditorSplit').applyPersistedTabSplit
  const applyRolldownPolyfills: typeof import('./lib/rolldown-polyfill').applyRolldownPolyfills
  const applyTrailingNewlineStyle: typeof import('./lib/local-md-snapshot').applyTrailingNewlineStyle
  const assignExistingStableId: typeof import('./lib/local-page-idmap').assignExistingStableId
  const badgeVariants: typeof import('./components/ui/badge').badgeVariants
  const blobToBase64: typeof import('./lib/imageProcessor').blobToBase64
  const blocksToHTML: typeof import('./lib/export/index').blocksToHTML
  const blocksToMarkdown: typeof import('./lib/export/index').blocksToMarkdown
  const buildAiContextBundle: typeof import('./lib/ai-write/index').buildAiContextBundle
  const buildAiWorkspaceUserPrompt: typeof import('./lib/ai-write/index').buildAiWorkspaceUserPrompt
  const buildAiWritePlan: typeof import('./lib/ai-write/index').buildAiWritePlan
  const buildInheritedPasteBlocks: typeof import('./components/editor/utils/multilinePaste').buildInheritedPasteBlocks
  const buildLocalFolderPickerItems: typeof import('./lib/local-folder-target').buildLocalFolderPickerItems
  const buildLocalPageId: typeof import('./lib/local-folder-scanner').buildLocalPageId
  const buildNotebookCardTheme: typeof import('./lib/imageExport/index').buildNotebookCardTheme
  const buildQuickNoteDraftPage: typeof import('./stores/useQuickNote').buildQuickNoteDraftPage
  const buildSinglePageExport: typeof import('./lib/export/index').buildSinglePageExport
  const buildSoftWrapInlineFromMarkdown: typeof import('./components/editor/utils/softWrapPaste').buildSoftWrapInlineFromMarkdown
  const buildSoftWrapPasteInline: typeof import('./components/editor/utils/softWrapPaste').buildSoftWrapPasteInline
  const buttonVariants: typeof import('./components/ui/button').buttonVariants
  const cache: typeof import('react').cache
  const cachePasteTarget: typeof import('./components/editor/hooks/useEditorPaste').cachePasteTarget
  const cacheSignal: typeof import('react').cacheSignal
  const canonicalizeRecordedShortcut: typeof import('./lib/shortcut-platform').canonicalizeRecordedShortcut
  const clampQuickNoteZoom: typeof import('./stores/useQuickNote').clampQuickNoteZoom
  const classifyAiLineText: typeof import('./lib/ai-write/index').classifyAiLineText
  const cleanAssetDestination: typeof import('./lib/local-folder-asset-maintenance').cleanAssetDestination
  const clearAllLocalMdSnapshots: typeof import('./lib/local-md-snapshot').clearAllLocalMdSnapshots
  const clearEditorSelectedBlocksCache: typeof import('./components/editor/utils/selection').clearEditorSelectedBlocksCache
  const clearLocalFolderFileDropTarget: typeof import('./lib/local-folder-file-drop-target').clearLocalFolderFileDropTarget
  const clearLocalPageMetadataCache: typeof import('./stores/pages/index').clearLocalPageMetadataCache
  const clearStartupSettling: typeof import('./lib/appearance').clearStartupSettling
  const clearWorkspaceStartupSelection: typeof import('./lib/workspaceStartup').clearWorkspaceStartupSelection
  const clipboardHasPasteableImage: typeof import('./components/editor/utils/pasteClipboardImage').clipboardHasPasteableImage
  const clipboardHasPasteableMedia: typeof import('./components/editor/utils/pasteClipboardImage').clipboardHasPasteableMedia
  const clonePageContent: typeof import('./components/editor/utils/blocknote-content/index').clonePageContent
  const closeAllOverlays: typeof import('./lib/closeAllOverlays').closeAllOverlays
  const clsx: typeof import('clsx').clsx
  const cn: typeof import('./lib/utils').cn
  const coerceGeneratedBlocksToExpectedType: typeof import('./lib/ai-write/index').coerceGeneratedBlocksToExpectedType
  const commitAiWritePlan: typeof import('./lib/ai-write/index').commitAiWritePlan
  const completePageTitleFocus: typeof import('./lib/page-title-focus').completePageTitleFocus
  const composerDraftHasContent: typeof import('./stores/useNotebookAiChats').composerDraftHasContent
  const compressIfNeeded: typeof import('./lib/imageProcessor').compressIfNeeded
  const compressImage: typeof import('./lib/imageProcessor').compressImage
  const computeEditorUiScale: typeof import('./lib/appearance').computeEditorUiScale
  const computeSidebarRowHeight: typeof import('./lib/appearance').computeSidebarRowHeight
  const consumeDiskWriteFailure: typeof import('./lib/diskWriteError').consumeDiskWriteFailure
  const consumePendingAssociatedMarkdownFiles: typeof import('./lib/openAssociatedMarkdown').consumePendingAssociatedMarkdownFiles
  const containsMarkdownTable: typeof import('./lib/markdownTableParser').containsMarkdownTable
  const convertImageBlobToPng: typeof import('./lib/imageProcessor').convertImageBlobToPng
  const countWords: typeof import('./components/editor/utils/content-text-extractor').countWords
  const createAiChatOnlyTarget: typeof import('./lib/ai-write/index').createAiChatOnlyTarget
  const createBlockTypeTransformSelectionSnapshot: typeof import('./lib/ai-write/index').createBlockTypeTransformSelectionSnapshot
  const createContext: typeof import('react').createContext
  const createDebounce: typeof import('./components/editor/utils/debounce').createDebounce
  const createDefaultQuickNoteSlotNames: typeof import('./stores/useQuickNote').createDefaultQuickNoteSlotNames
  const createEditorSafeContent: typeof import('./components/editor/utils/blocknote-content/index').createEditorSafeContent
  const createEmptyBlockNoteContent: typeof import('./components/editor/utils/blocknote-content/index').createEmptyBlockNoteContent
  const createEmptyLocalPageContent: typeof import('./components/editor/utils/blocknote-content/index').createEmptyLocalPageContent
  const createEmptyQuickNoteDrafts: typeof import('./stores/useQuickNote').createEmptyQuickNoteDrafts
  const createPageBodyBlockTypeTransformSnapshot: typeof import('./lib/ai-write/index').createPageBodyBlockTypeTransformSnapshot
  const createRef: typeof import('react').createRef
  const createStickyTargetFromResolvedTarget: typeof import('./lib/ai-write/index').createStickyTargetFromResolvedTarget
  const createVaultNotebook: typeof import('./lib/local-vault').createVaultNotebook
  const currentLocalNotebookRoot: typeof import('./lib/currentLocalPagePath').currentLocalNotebookRoot
  const currentLocalPagePath: typeof import('./lib/currentLocalPagePath').currentLocalPagePath
  const decodeUnsupportedMarkdownForDisk: typeof import('./lib/markdown-raw-guard').decodeUnsupportedMarkdownForDisk
  const deleteLocalMdSnapshot: typeof import('./lib/local-md-snapshot').deleteLocalMdSnapshot
  const deletePageWithUndo: typeof import('./lib/page-delete-actions').deletePageWithUndo
  const deleteWebdavBackup: typeof import('./lib/webdavSync').deleteWebdavBackup
  const describeDiskWriteError: typeof import('./lib/diskWriteError').describeDiskWriteError
  const detectBlockScopeHeuristic: typeof import('./lib/ai-block-scope').detectBlockScopeHeuristic
  const downloadWebdavBackup: typeof import('./lib/webdavSync').downloadWebdavBackup
  const editorSplitPersistKey: typeof import('./stores/useEditorSplit').editorSplitPersistKey
  const effectiveSingleTabMode: typeof import('./lib/tabMode').effectiveSingleTabMode
  const emptyBlock: typeof import('./components/editor/utils/blocknote-content/index').emptyBlock
  const encodeUnsupportedMarkdownForEditor: typeof import('./lib/markdown-raw-guard').encodeUnsupportedMarkdownForEditor
  const ensureBodyParagraphAfterTitle: typeof import('./components/editor/utils/blocknote-content/index').ensureBodyParagraphAfterTitle
  const ensureEditorFontAvailable: typeof import('./lib/fontLoader').ensureEditorFontAvailable
  const ensureFilenameAsTitle: typeof import('./lib/local-title-binding').ensureFilenameAsTitle
  const ensureFirstTitleHeading: typeof import('./components/editor/utils/blocknote-content/index').ensureFirstTitleHeading
  const ensurePersistentRemoteFont: typeof import('./lib/fontLoader').ensurePersistentRemoteFont
  const explodeAiGeneratedBlocks: typeof import('./lib/ai-write/index').explodeAiGeneratedBlocks
  const exportNotebooks: typeof import('./lib/export/index').exportNotebooks
  const exportPageToImage: typeof import('./lib/imageExport/index').exportPageToImage
  const exportSelectionToImage: typeof import('./lib/imageExport/index').exportSelectionToImage
  const exportToHTML: typeof import('./lib/export/index').exportToHTML
  const exportToImage: typeof import('./lib/imageExport/index').exportToImage
  const exportToJSON: typeof import('./lib/export/index').exportToJSON
  const exportToMarkdown: typeof import('./lib/export/index').exportToMarkdown
  const exportToPDF: typeof import('./lib/export/index').exportToPDF
  const exportToWord: typeof import('./lib/docxExport/index').exportToWord
  const extractAssetReferencesFromMarkdown: typeof import('./lib/local-folder-asset-maintenance').extractAssetReferencesFromMarkdown
  const extractBlockNoteTitle: typeof import('./components/editor/utils/blocknote-content/index').extractBlockNoteTitle
  const extractBlocksInRange: typeof import('./lib/ai-block-scope').extractBlocksInRange
  const extractClipboardImageFiles: typeof import('./components/editor/utils/pasteClipboardImage').extractClipboardImageFiles
  const extractFirstHeadingText: typeof import('./lib/local-title-binding').extractFirstHeadingText
  const extractFrontmatter: typeof import('./lib/markdown-raw-guard').extractFrontmatter
  const extractPlainText: typeof import('./components/editor/utils/blocknote-content/index').extractPlainText
  const extractStructureSummary: typeof import('./components/editor/utils/content-text-extractor').extractStructureSummary
  const extractTextFromContent: typeof import('./components/editor/utils/content-text-extractor').extractTextFromContent
  const extractTitleFromContent: typeof import('./components/editor/utils/content-text-extractor').extractTitleFromContent
  const fetchCustomAIModels: typeof import('./lib/ai-provider/index').fetchCustomAIModels
  const fileNavKeyForTab: typeof import('./stores/useFileNavHistory').fileNavKeyForTab
  const fileStorage: typeof import('./lib/fileStorage').fileStorage
  const findActivePageMentionQuery: typeof import('./components/editor/utils/slashMenuPolicy').findActivePageMentionQuery
  const findContainingLocalFolderNotebook: typeof import('./lib/openAssociatedMarkdown').findContainingLocalFolderNotebook
  const findNonOverlappingToolbarPosition: typeof import('./components/editor/utils/formattingToolbarPosition').findNonOverlappingToolbarPosition
  const findPseudoStructureMarkers: typeof import('./lib/ai-write/index').findPseudoStructureMarkers
  const findTabLeaf: typeof import('./stores/useEditorSplit').findTabLeaf
  const finishPasteAtAnchor: typeof import('./components/editor/hooks/useEditorPaste').finishPasteAtAnchor
  const flattenParsedBlocksToSoftWrapInline: typeof import('./components/editor/utils/softWrapPaste').flattenParsedBlocksToSoftWrapInline
  const flushEditorContent: typeof import('./stores/pages/index').flushEditorContent
  const flushSidebarViewPersist: typeof import('./stores/useSidebarView').flushSidebarViewPersist
  const flushUToolsStorageWrites: typeof import('./lib/storage').flushUToolsStorageWrites
  const focusPastedBlock: typeof import('./components/editor/utils/pasteAtCursor').focusPastedBlock
  const formatAttachmentSize: typeof import('./lib/fileStorage').formatAttachmentSize
  const formatDualShortcut: typeof import('./lib/onboardingContent').formatDualShortcut
  const formatDualShortcutGroup: typeof import('./lib/onboardingContent').formatDualShortcutGroup
  const formatLocalFolderOpenAppName: typeof import('./lib/local-folder-open-apps').formatLocalFolderOpenAppName
  const formatShortcut: typeof import('./lib/utils').formatShortcut
  const formatShortcutToken: typeof import('./lib/shortcut-platform').formatShortcutToken
  const formatSystemModifier: typeof import('./lib/shortcut-platform').formatSystemModifier
  const forwardRef: typeof import('react').forwardRef
  const generateDocxBuffer: typeof import('./lib/docxExport/index').generateDocxBuffer
  const generateExportZip: typeof import('./lib/export/index').generateExportZip
  const getAIAvailability: typeof import('./lib/ai-provider/index').getAIAvailability
  const getAIProviderPreset: typeof import('./lib/ai-provider/index').getAIProviderPreset
  const getActiveDraftContent: typeof import('./stores/useQuickNote').getActiveDraftContent
  const getActiveGooseNoteEditor: typeof import('./components/editor/utils/selection').getActiveGooseNoteEditor
  const getApiKeyMissingMessage: typeof import('./lib/ai-provider/index').getApiKeyMissingMessage
  const getAttachmentBadgeLabel: typeof import('./lib/fileStorage').getAttachmentBadgeLabel
  const getBlockTypeTransformSignature: typeof import('./lib/ai-write/index').getBlockTypeTransformSignature
  const getBlockTypeTransformTargetLabel: typeof import('./lib/ai-write/index').getBlockTypeTransformTargetLabel
  const getCardTheme: typeof import('./lib/imageExport/index').getCardTheme
  const getCompactSlashMenuFloatingOptions: typeof import('./components/editor/utils/compactSlashMenuFloating').getCompactSlashMenuFloatingOptions
  const getContentFrontmatterBody: typeof import('./lib/local-frontmatter').getContentFrontmatterBody
  const getContentSignature: typeof import('./components/editor/utils/blocknote-content/index').getContentSignature
  const getCustomAIApiKey: typeof import('./lib/ai-provider/index').getCustomAIApiKey
  const getCustomAIBaseURL: typeof import('./lib/ai-provider/index').getCustomAIBaseURL
  const getDbStorageItem: typeof import('./lib/storage').getDbStorageItem
  const getDefaultCustomAIBaseURL: typeof import('./lib/ai-provider/index').getDefaultCustomAIBaseURL
  const getEditorFontFamilies: typeof import('./lib/fontLoader').getEditorFontFamilies
  const getEditorSelectedBlocksForExport: typeof import('./components/editor/utils/selection').getEditorSelectedBlocksForExport
  const getEditorUiScale: typeof import('./components/editor/utils/editorContextUi').getEditorUiScale
  const getElementFromNode: typeof import('./components/editor/utils/selection').getElementFromNode
  const getFileUploadAvailability: typeof import('./lib/fileUploadAvailability').getFileUploadAvailability
  const getFixedAppShortcuts: typeof import('./lib/fixed-app-shortcuts').getFixedAppShortcuts
  const getFormattingToolbarReferenceRect: typeof import('./components/editor/utils/formattingToolbarReference').getFormattingToolbarReferenceRect
  const getImageFromClipboard: typeof import('./lib/imageProcessor').getImageFromClipboard
  const getLocalFolderFileDropTarget: typeof import('./lib/local-folder-file-drop-target').getLocalFolderFileDropTarget
  const getLocalMdSnapshot: typeof import('./lib/local-md-snapshot').getLocalMdSnapshot
  const getMaxFileAttachmentSize: typeof import('./lib/fileStorage').getMaxFileAttachmentSize
  const getModifierOnlyShortcut: typeof import('./lib/shortcut-match').getModifierOnlyShortcut
  const getMultiBlockToolbarEdgeRect: typeof import('./components/editor/utils/formattingToolbarReference').getMultiBlockToolbarEdgeRect
  const getNotebookAiTabPageId: typeof import('./stores/useTabs').getNotebookAiTabPageId
  const getPageContainingFolderId: typeof import('./lib/local-folder-target').getPageContainingFolderId
  const getPageParentDirectoryId: typeof import('./lib/local-folder-target').getPageParentDirectoryId
  const getPageTitle: typeof import('./components/editor/utils/page-title').getPageTitle
  const getPlatformKind: typeof import('./lib/utils').getPlatformKind
  const getPrimaryModifierKeyDisplay: typeof import('./lib/utils').getPrimaryModifierKeyDisplay
  const getPrimaryModifierKeyLabel: typeof import('./lib/utils').getPrimaryModifierKeyLabel
  const getProviderCredentialSlots: typeof import('./lib/ai-provider/index').getProviderCredentialSlots
  const getProviderFixedBaseURL: typeof import('./lib/ai-provider/index').getProviderFixedBaseURL
  const getQuickNoteSlotName: typeof import('./stores/useQuickNote').getQuickNoteSlotName
  const getQuicknoteSlashMenuFloatingOptions: typeof import('./components/editor/utils/quicknoteSlashMenuFloating').getQuicknoteSlashMenuFloatingOptions
  const getRandomTip: typeof import('./lib/tips').getRandomTip
  const getScaledEditorUiPx: typeof import('./components/editor/utils/editorContextUi').getScaledEditorUiPx
  const getSelectedCellPlainText: typeof import('./components/editor/utils/selection').getSelectedCellPlainText
  const getSelectedImageUrl: typeof import('./components/editor/utils/selection').getSelectedImageUrl
  const getSelectedPlainTextContext: typeof import('./components/editor/utils/selection').getSelectedPlainTextContext
  const getSettingsProviderId: typeof import('./lib/ai-provider/index').getSettingsProviderId
  const getShortcutFromMouseEvent: typeof import('./lib/shortcut-match').getShortcutFromMouseEvent
  const getStoredAIModelOptions: typeof import('./lib/ai-provider/index').getStoredAIModelOptions
  const hasStructuredBlocks: typeof import('./components/editor/utils/blocknote-content/index').hasStructuredBlocks
  const hasStyledSoftWrapItems: typeof import('./components/editor/utils/softWrapPaste').hasStyledSoftWrapItems
  const hasWholePageBlockTypeTransformScope: typeof import('./lib/ai-write/index').hasWholePageBlockTypeTransformScope
  const htmlHasInlineFormatting: typeof import('./components/editor/utils/softWrapPaste').htmlHasInlineFormatting
  const htmlHasNonDefaultGooseBlockAttrs: typeof import('./components/editor/utils/clipboard').htmlHasNonDefaultGooseBlockAttrs
  const htmlHasNonTextPasteBlocks: typeof import('./components/editor/utils/multilinePaste').htmlHasNonTextPasteBlocks
  const htmlHasPreservableFormatting: typeof import('./components/editor/utils/clipboard').htmlHasPreservableFormatting
  const htmlToPlainTextForPaste: typeof import('./components/editor/utils/multilinePaste').htmlToPlainTextForPaste
  const importFile: typeof import('./lib/export/index').importFile
  const importFromJSON: typeof import('./lib/export/index').importFromJSON
  const importFromMarkdown: typeof import('./lib/export/index').importFromMarkdown
  const importMarkdownFragment: typeof import('./lib/export/index').importMarkdownFragment
  const importNotebooksFromZip: typeof import('./lib/export/index').importNotebooksFromZip
  const importTextFilesToLocalFolder: typeof import('./lib/local-folder-import').importTextFilesToLocalFolder
  const inferProviderIdFromSettings: typeof import('./lib/ai-provider/index').inferProviderIdFromSettings
  const insertSoftWrappedInline: typeof import('./components/editor/utils/softWrapPaste').insertSoftWrappedInline
  const insertSoftWrappedLines: typeof import('./components/editor/utils/softWrapPaste').insertSoftWrappedLines
  const inspectNotebookImportZip: typeof import('./lib/export/index').inspectNotebookImportZip
  const inspectPasteContainer: typeof import('./components/editor/utils/multilinePaste').inspectPasteContainer
  const isAIProviderId: typeof import('./lib/ai-provider/index').isAIProviderId
  const isBackupFileName: typeof import('./lib/webdavSync').isBackupFileName
  const isBlockNoteContent: typeof import('./components/editor/utils/blocknote-content/index').isBlockNoteContent
  const isBlockTypeTransformSelectionSnapshot: typeof import('./lib/ai-write/index').isBlockTypeTransformSelectionSnapshot
  const isBottomEditorBlankClick: typeof import('./components/editor/utils/selection').isBottomEditorBlankClick
  const isDeepSeekProModel: typeof import('./lib/ai-provider/index').isDeepSeekProModel
  const isDescendantPage: typeof import('./lib/local-folder-target').isDescendantPage
  const isDiskContentMatchingSnapshot: typeof import('./lib/local-md-snapshot').isDiskContentMatchingSnapshot
  const isDuplicateCompositionEndChange: typeof import('./hooks/useImeInput').isDuplicateCompositionEndChange
  const isElectronHost: typeof import('./lib/local-vault').isElectronHost
  const isElectronLocalFolderDirectory: typeof import('./lib/sidebarPageNavigation').isElectronLocalFolderDirectory
  const isEmptyInlineBlock: typeof import('./components/editor/utils/pasteAtCursor').isEmptyInlineBlock
  const isExternalFileDrag: typeof import('./lib/local-folder-target').isExternalFileDrag
  const isImageUploadFile: typeof import('./components/editor/utils/pasteClipboardImage').isImageUploadFile
  const isImeKeyboardEvent: typeof import('./hooks/useImeInput').isImeKeyboardEvent
  const isInsideToggle: typeof import('./components/editor/utils/toggleNesting').isInsideToggle
  const isInteractiveEditorTarget: typeof import('./components/editor/utils/selection').isInteractiveEditorTarget
  const isInternalAssetRef: typeof import('./lib/internalAssetRef').isInternalAssetRef
  const isLinkworthyText: typeof import('./components/editor/utils/clipboard').isLinkworthyText
  const isListPasteBlockType: typeof import('./components/editor/utils/multilinePaste').isListPasteBlockType
  const isLocalFolderDirectoryPage: typeof import('./lib/sidebarPageNavigation').isLocalFolderDirectoryPage
  const isLocalMdUnchanged: typeof import('./lib/local-md-snapshot').isLocalMdUnchanged
  const isLocalPageFrontmatterSettingsUpdate: typeof import('./lib/local-frontmatter').isLocalPageFrontmatterSettingsUpdate
  const isMacPlatform: typeof import('./lib/utils').isMacPlatform
  const isNotebookAiTab: typeof import('./stores/useTabs').isNotebookAiTab
  const isPageMentionBoundaryChar: typeof import('./components/editor/utils/slashMenuPolicy').isPageMentionBoundaryChar
  const isPageTitleAutoFocusProtected: typeof import('./lib/page-title-focus').isPageTitleAutoFocusProtected
  const isPageTitleFocusRequested: typeof import('./lib/page-title-focus').isPageTitleFocusRequested
  const isPasteableClipboardImageFile: typeof import('./components/editor/utils/pasteClipboardImage').isPasteableClipboardImageFile
  const isPasteableClipboardVideoFile: typeof import('./components/editor/utils/pasteClipboardImage').isPasteableClipboardVideoFile
  const isPathInsideNotebookRoot: typeof import('./lib/currentLocalPagePath').isPathInsideNotebookRoot
  const isPinyinQuery: typeof import('./lib/pinyin-search').isPinyinQuery
  const isPlatformPrimaryModifierEvent: typeof import('./lib/shortcut-platform').isPlatformPrimaryModifierEvent
  const isQuickNoteDraftEmpty: typeof import('./stores/useQuickNote').isQuickNoteDraftEmpty
  const isRandomPageIcon: typeof import('./lib/randomPageIcon').isRandomPageIcon
  const isSpecialTab: typeof import('./stores/useTabs').isSpecialTab
  const isStatMatchingSnapshot: typeof import('./lib/local-md-snapshot').isStatMatchingSnapshot
  const isSuggestionMenuAcceptKey: typeof import('./components/editor/utils/slashMenuPolicy').isSuggestionMenuAcceptKey
  const isSupportedTextImportFile: typeof import('./lib/local-folder-import').isSupportedTextImportFile
  const isToggleBlock: typeof import('./components/editor/utils/toggleNesting').isToggleBlock
  const isUnsavedLocalPage: typeof import('./lib/unsavedLocalPage').isUnsavedLocalPage
  const isValidImageUrl: typeof import('./lib/imageProcessor').isValidImageUrl
  const isValidUrl: typeof import('./components/editor/utils/clipboard').isValidUrl
  const isVideoUploadFile: typeof import('./lib/videoProcessor').isVideoUploadFile
  const isWikiMediaTarget: typeof import('./lib/wikiLink').isWikiMediaTarget
  const jsonContentToMarkdown: typeof import('./lib/export/index').jsonContentToMarkdown
  const lazy: typeof import('react').lazy
  const listWebdavBackups: typeof import('./lib/webdavSync').listWebdavBackups
  const loadQuickNoteSlotNames: typeof import('./stores/useQuickNote').loadQuickNoteSlotNames
  const localAssetPaths: typeof import('./lib/local-folder-asset-maintenance').localAssetPaths
  const localFileTitleFromPath: typeof import('./lib/local-folder-scanner').localFileTitleFromPath
  const localPageHasPersistableContent: typeof import('./lib/unsavedLocalPage').localPageHasPersistableContent
  const looksLikeBlockStructure: typeof import('./components/editor/utils/clipboard').looksLikeBlockStructure
  const looksLikeMarkdownFragment: typeof import('./components/editor/utils/clipboard').looksLikeMarkdownFragment
  const looksLikeMermaidDiagram: typeof import('./components/editor/utils/clipboard').looksLikeMermaidDiagram
  const markSelfWrite: typeof import('./lib/local-md-snapshot').markSelfWrite
  const markStartupSettling: typeof import('./lib/appearance').markStartupSettling
  const markUserInteraction: typeof import('./lib/editor-interaction-signal').markUserInteraction
  const matchModifierOnlyShortcutKey: typeof import('./lib/shortcut-match').matchModifierOnlyShortcutKey
  const matchModifierOnlyShortcutKeyDown: typeof import('./lib/shortcut-match').matchModifierOnlyShortcutKeyDown
  const matchMouseShortcut: typeof import('./lib/shortcut-match').matchMouseShortcut
  const matchShortcut: typeof import('./lib/shortcut-match').matchShortcut
  const materializeImageBlob: typeof import('./lib/imageProcessor').materializeImageBlob
  const memo: typeof import('react').memo
  const mentionTriggerDeleteRange: typeof import('./components/editor/utils/slashMenuPolicy').mentionTriggerDeleteRange
  const mergeLocalPageSettingsIntoFrontmatter: typeof import('./lib/local-frontmatter').mergeLocalPageSettingsIntoFrontmatter
  const mergeSettingsIntoFrontmatterHeader: typeof import('./lib/local-frontmatter').mergeSettingsIntoFrontmatterHeader
  const migrateCodeStyleTo2026: typeof import('./lib/code-style-migration').migrateCodeStyleTo2026
  const migrateLocalPageIdMapEntry: typeof import('./lib/local-page-idmap').migrateLocalPageIdMapEntry
  const migrateNotebookAiChatsState: typeof import('./stores/useNotebookAiChats').migrateNotebookAiChatsState
  const needsBodyParagraphAfterTitle: typeof import('./components/editor/utils/blocknote-content/index').needsBodyParagraphAfterTitle
  const normalizeBaseUrl: typeof import('./lib/webdavSync').normalizeBaseUrl
  const normalizeBlockContent: typeof import('./components/editor/utils/blocknote-content/index').normalizeBlockContent
  const normalizeBlocks: typeof import('./components/editor/utils/blocknote-content/index').normalizeBlocks
  const normalizeCardThemeId: typeof import('./lib/imageExport/index').normalizeCardThemeId
  const normalizeClipboardLineEndings: typeof import('./components/editor/utils/clipboard').normalizeClipboardLineEndings
  const normalizeEditorUiScale: typeof import('./components/editor/utils/editorContextUi').normalizeEditorUiScale
  const normalizeExternalUrl: typeof import('./lib/openExternalUrl').normalizeExternalUrl
  const normalizeGeneratedStructureMarkdown: typeof import('./lib/ai-write/index').normalizeGeneratedStructureMarkdown
  const normalizeHeadingSectionFold: typeof import('./components/editor/utils/blocknote-content/index').normalizeHeadingSectionFold
  const normalizeHeadingToggleableFlags: typeof import('./components/editor/utils/blocknote-content/index').normalizeHeadingToggleableFlags
  const normalizeMarkdownPasteText: typeof import('./components/editor/utils/clipboard').normalizeMarkdownPasteText
  const normalizePageContent: typeof import('./components/editor/utils/blocknote-content/index').normalizePageContent
  const normalizePageTitle: typeof import('./components/editor/utils/page-title').normalizePageTitle
  const normalizeRemoteDir: typeof import('./lib/webdavSync').normalizeRemoteDir
  const normalizeShortcutForConflict: typeof import('./lib/shortcut-platform').normalizeShortcutForConflict
  const normalizeShortcutToken: typeof import('./lib/shortcut-platform').normalizeShortcutToken
  const normalizeWatermarkConfig: typeof import('./lib/imageExport/index').normalizeWatermarkConfig
  const normalizeWikiPath: typeof import('./lib/wikiLink').normalizeWikiPath
  const onboardingChildPageContent: typeof import('./lib/onboardingContent').onboardingChildPageContent
  const onboardingPageContent: typeof import('./lib/onboardingContent').onboardingPageContent
  const onboardingSecondChildContent: typeof import('./lib/onboardingContent').onboardingSecondChildContent
  const onboardingThirdChildContent: typeof import('./lib/onboardingContent').onboardingThirdChildContent
  const openAssociatedMarkdownFile: typeof import('./lib/openAssociatedMarkdown').openAssociatedMarkdownFile
  const openAssociatedMarkdownFiles: typeof import('./lib/openAssociatedMarkdown').openAssociatedMarkdownFiles
  const openExternalUrl: typeof import('./lib/openExternalUrl').openExternalUrl
  const openPageFromSidebar: typeof import('./lib/sidebarPageNavigation').openPageFromSidebar
  const openResourceExternally: typeof import('./components/editor/utils/openResourceExternally').openResourceExternally
  const pageDirectory: typeof import('./lib/currentLocalPagePath').pageDirectory
  const pageFileNavKey: typeof import('./stores/useFileNavHistory').pageFileNavKey
  const pageHasLocalSidecarAttachments: typeof import('./lib/export/index').pageHasLocalSidecarAttachments
  const pageSettingsFromMarkdown: typeof import('./lib/local-frontmatter').pageSettingsFromMarkdown
  const parseFileNavKey: typeof import('./stores/useFileNavHistory').parseFileNavKey
  const parseLocalFrontmatterBlob: typeof import('./lib/local-frontmatter').parseLocalFrontmatterBlob
  const parseLocalMarkdownContent: typeof import('./lib/local-folder-scanner').parseLocalMarkdownContent
  const parseMarkdownLink: typeof import('./components/editor/utils/clipboard').parseMarkdownLink
  const parseMarkdownTableToHtml: typeof import('./lib/markdownTableParser').parseMarkdownTableToHtml
  const parseMarkdownToHtml: typeof import('./lib/markdownTableParser').parseMarkdownToHtml
  const parsePersistedQuickNoteSlotNames: typeof import('./stores/useQuickNote').parsePersistedQuickNoteSlotNames
  const parseWikiLinkInner: typeof import('./lib/wikiLink').parseWikiLinkInner
  const pasteBlocksAtCursor: typeof import('./components/editor/utils/pasteAtCursor').pasteBlocksAtCursor
  const pasteClipboardFilesFromClipboard: typeof import('./components/editor/utils/pasteClipboardFilesFromClipboard').pasteClipboardFilesFromClipboard
  const pasteClipboardHtmlAsBlocks: typeof import('./components/editor/hooks/useEditorPaste').pasteClipboardHtmlAsBlocks
  const pasteLinesAsBlocks: typeof import('./components/editor/hooks/useEditorPaste').pasteLinesAsBlocks
  const permanentlyDeletePageWithCleanup: typeof import('./lib/page-delete-actions').permanentlyDeletePageWithCleanup
  const persistQuickNoteSlotNames: typeof import('./stores/useQuickNote').persistQuickNoteSlotNames
  const pickRandomPageIcon: typeof import('./lib/randomPageIcon').pickRandomPageIcon
  const pickVaultParentDirectory: typeof import('./lib/local-vault').pickVaultParentDirectory
  const pinyinMatchIndices: typeof import('./lib/pinyin-search').pinyinMatchIndices
  const plainHasGooseMarkdownMarkers: typeof import('./components/editor/hooks/useEditorPaste').plainHasGooseMarkdownMarkers
  const planBlockTypeTransform: typeof import('./lib/ai-write/index').planBlockTypeTransform
  const planMultilinePaste: typeof import('./components/editor/utils/multilinePaste').planMultilinePaste
  const preloadFonts: typeof import('./lib/fontLoader').preloadFonts
  const prepareWorkspaceStartup: typeof import('./lib/workspaceStartup').prepareWorkspaceStartup
  const pruneLocalPageIdMap: typeof import('./lib/local-page-idmap').pruneLocalPageIdMap
  const readDbStorageJSON: typeof import('./lib/storage').readDbStorageJSON
  const readLiveEditorSelectedBlocks: typeof import('./components/editor/utils/selection').readLiveEditorSelectedBlocks
  const readLocalPageIdMap: typeof import('./lib/local-page-idmap').readLocalPageIdMap
  const readPersistentDismissState: typeof import('./lib/dismiss-state').readPersistentDismissState
  const readRecentLocalFolderTargets: typeof import('./lib/local-folder-target').readRecentLocalFolderTargets
  const reconcilePageMentionSuggestionMenu: typeof import('./components/editor/utils/slashMenuPolicy').reconcilePageMentionSuggestionMenu
  const reconcileSlashSuggestionMenu: typeof import('./components/editor/utils/slashMenuPolicy').reconcileSlashSuggestionMenu
  const recoverQuickNoteDrafts: typeof import('./stores/useQuickNote').recoverQuickNoteDrafts
  const releaseStartupSettlingAfterPaint: typeof import('./lib/appearance').releaseStartupSettlingAfterPaint
  const rememberDiskWriteFailure: typeof import('./lib/diskWriteError').rememberDiskWriteFailure
  const rememberEditorSelectedBlocks: typeof import('./components/editor/utils/selection').rememberEditorSelectedBlocks
  const rememberLocalFolderTarget: typeof import('./lib/local-folder-target').rememberLocalFolderTarget
  const removeDbStorageItem: typeof import('./lib/storage').removeDbStorageItem
  const removeLocalPageIdMap: typeof import('./lib/local-page-idmap').removeLocalPageIdMap
  const renderExportHtml: typeof import('./lib/export/index').renderExportHtml
  const renderPageToDocxBlob: typeof import('./lib/docxExport/index').renderPageToDocxBlob
  const renderWorkspaceAfterStartup: typeof import('./lib/workspaceStartup').renderWorkspaceAfterStartup
  const requestPageTitleFocus: typeof import('./lib/page-title-focus').requestPageTitleFocus
  const resolveAccentRuntimeTokens: typeof import('./lib/accentColor').resolveAccentRuntimeTokens
  const resolveActiveProtocol: typeof import('./lib/ai-provider/index').resolveActiveProtocol
  const resolveAiTargetFromSelection: typeof import('./lib/ai-write/index').resolveAiTargetFromSelection
  const resolveAiTargetIntent: typeof import('./lib/ai-write/index').resolveAiTargetIntent
  const resolveAiTargetReference: typeof import('./lib/ai-write/index').resolveAiTargetReference
  const resolveAiTargetSelection: typeof import('./lib/ai-write/index').resolveAiTargetSelection
  const resolveBlockTypeTransformIntent: typeof import('./lib/ai-write/index').resolveBlockTypeTransformIntent
  const resolveCardTheme: typeof import('./lib/imageExport/index').resolveCardTheme
  const resolveDropTargetParentId: typeof import('./lib/local-folder-target').resolveDropTargetParentId
  const resolveExplicitBlockTypeTarget: typeof import('./lib/ai-write/index').resolveExplicitBlockTypeTarget
  const resolveGeneratedBlockStructureExpectation: typeof import('./lib/ai-write/index').resolveGeneratedBlockStructureExpectation
  const resolveImageMimeForUpload: typeof import('./components/editor/utils/pasteClipboardImage').resolveImageMimeForUpload
  const resolveImportParentForDrop: typeof import('./lib/local-folder-import').resolveImportParentForDrop
  const resolveInheritedPasteBlockType: typeof import('./components/editor/utils/multilinePaste').resolveInheritedPasteBlockType
  const resolveLocalFolderImportParentId: typeof import('./lib/local-folder-target').resolveLocalFolderImportParentId
  const resolveModModifier: typeof import('./lib/shortcut-platform').resolveModModifier
  const resolveNotebookLandingPageId: typeof import('./lib/notebookNavigation').resolveNotebookLandingPageId
  const resolveOrCreateStableId: typeof import('./lib/local-page-idmap').resolveOrCreateStableId
  const resolvePageMentionNavigation: typeof import('./lib/pageMentionNavigation').resolvePageMentionNavigation
  const resolvePasteAnchor: typeof import('./components/editor/hooks/useEditorPaste').resolvePasteAnchor
  const resolvePasteLines: typeof import('./components/editor/utils/multilinePaste').resolvePasteLines
  const resolvePhysicalResourcePath: typeof import('./components/editor/utils/openResourceExternally').resolvePhysicalResourcePath
  const resolveProtocolForProvider: typeof import('./lib/ai-provider/index').resolveProtocolForProvider
  const resolveTheme: typeof import('./hooks/useResolvedTheme').resolveTheme
  const resolveTooltipDelayDuration: typeof import('./components/ui/tooltip-delay').resolveTooltipDelayDuration
  const resolveWikiLinkTarget: typeof import('./lib/pageMentionNavigation').resolveWikiLinkTarget
  const resolvedTargetToSelection: typeof import('./lib/ai-write/index').resolvedTargetToSelection
  const restoreLastNoteIfNeeded: typeof import('./lib/workspaceStartup').restoreLastNoteIfNeeded
  const restoreMissingReferencedLocalAssets: typeof import('./lib/local-folder-asset-maintenance').restoreMissingReferencedLocalAssets
  const restorePageWithToast: typeof import('./lib/page-delete-actions').restorePageWithToast
  const rewriteAiStructureLine: typeof import('./lib/ai-write/index').rewriteAiStructureLine
  const runAIText: typeof import('./lib/ai-provider/index').runAIText
  const runAITextStream: typeof import('./lib/ai-provider/index').runAITextStream
  const runCodeStyleMigration2026: typeof import('./lib/code-style-migration').runCodeStyleMigration2026
  const sanitizeFileName: typeof import('./lib/fileStorage').sanitizeFileName
  const sanitizeFilenameSegment: typeof import('./lib/local-title-binding').sanitizeFilenameSegment
  const saveBlobAndReveal: typeof import('./lib/export/index').saveBlobAndReveal
  const scanLocalFolderPages: typeof import('./lib/local-folder-scanner').scanLocalFolderPages
  const scanUnreferencedLocalAssets: typeof import('./lib/local-folder-asset-maintenance').scanUnreferencedLocalAssets
  const selectExpandedIds: typeof import('./stores/useSidebarView').selectExpandedIds
  const selectFavoritesCollapsed: typeof import('./stores/useSidebarView').selectFavoritesCollapsed
  const selectFocusedId: typeof import('./stores/useSidebarView').selectFocusedId
  const selectSelectedId: typeof import('./stores/useSidebarView').selectSelectedId
  const serializeQuickNoteSlotNames: typeof import('./stores/useQuickNote').serializeQuickNoteSlotNames
  const serializeWikiLinkMarkdown: typeof import('./lib/wikiLink').serializeWikiLinkMarkdown
  const setDbStorageItem: typeof import('./lib/storage').setDbStorageItem
  const setLocalFolderFileDropTarget: typeof import('./lib/local-folder-file-drop-target').setLocalFolderFileDropTarget
  const setLocalMdSnapshot: typeof import('./lib/local-md-snapshot').setLocalMdSnapshot
  const shortcutHasModifier: typeof import('./lib/shortcut-match').shortcutHasModifier
  const shouldIgnoreEntry: typeof import('./lib/local-folder-scanner').shouldIgnoreEntry
  const shouldIgnoreLocalRelativePath: typeof import('./lib/local-folder-scanner').shouldIgnoreLocalRelativePath
  const shouldIsolateTitleStructurePaste: typeof import('./components/editor/hooks/useEditorPaste').shouldIsolateTitleStructurePaste
  const shouldOpenPageMentionSuggestionMenu: typeof import('./components/editor/utils/slashMenuPolicy').shouldOpenPageMentionSuggestionMenu
  const shouldOpenSlashSuggestionMenu: typeof import('./components/editor/utils/slashMenuPolicy').shouldOpenSlashSuggestionMenu
  const shouldPasteClipboardAsBlocks: typeof import('./components/editor/hooks/useEditorPaste').shouldPasteClipboardAsBlocks
  const shouldPasteHtmlAsBlocks: typeof import('./components/editor/hooks/useEditorPaste').shouldPasteHtmlAsBlocks
  const shouldPreferVisibleSelectionText: typeof import('./components/editor/utils/clipboard').shouldPreferVisibleSelectionText
  const shouldPreserveStartupSelection: typeof import('./lib/workspaceStartup').shouldPreserveStartupSelection
  const shouldShowImageExportLivePreview: typeof import('./lib/imageExport/index').shouldShowImageExportLivePreview
  const shouldShowImageExportOptionsCorner: typeof import('./lib/imageExport/index').shouldShowImageExportOptionsCorner
  const shouldSkipAppHotkeyEvent: typeof import('./hooks/useImeInput').shouldSkipAppHotkeyEvent
  const shouldSplitMultilinePaste: typeof import('./components/editor/utils/multilinePaste').shouldSplitMultilinePaste
  const shouldSuppressSidebarSelect: typeof import('./lib/sidebarPageNavigation').shouldSuppressSidebarSelect
  const shouldUploadViaImageStorage: typeof import('./components/editor/utils/pasteClipboardImage').shouldUploadViaImageStorage
  const simpleExtractText: typeof import('./components/editor/utils/blocknote-content/index').simpleExtractText
  const sortNotebooksByOrder: typeof import('./stores/useNotebooks').sortNotebooksByOrder
  const splitFilePath: typeof import('./lib/local-title-binding').splitFilePath
  const splitPlainTextPasteLines: typeof import('./components/editor/utils/multilinePaste').splitPlainTextPasteLines
  const startTransition: typeof import('react').startTransition
  const stickyTargetToSelection: typeof import('./lib/ai-write/index').stickyTargetToSelection
  const stripComposerDraftImages: typeof import('./stores/useNotebookAiChats').stripComposerDraftImages
  const stripInheritedListPrefix: typeof import('./components/editor/utils/multilinePaste').stripInheritedListPrefix
  const stripMarkdownHardBreaks: typeof import('./components/editor/utils/clipboard').stripMarkdownHardBreaks
  const stripWikiMarkdownExtension: typeof import('./lib/wikiLink').stripWikiMarkdownExtension
  const subscribePageTitleFocus: typeof import('./lib/page-title-focus').subscribePageTitleFocus
  const syncAccentColorCssVars: typeof import('./lib/accentColor').syncAccentColorCssVars
  const testWebdavConnection: typeof import('./lib/webdavSync').testWebdavConnection
  const titleHeadingBlock: typeof import('./components/editor/utils/blocknote-content/index').titleHeadingBlock
  const toCssFontFamily: typeof import('./lib/fontLoader').toCssFontFamily
  const toDiskWriteError: typeof import('./lib/diskWriteError').toDiskWriteError
  const toInsertableInlineContent: typeof import('./components/editor/utils/softWrapPaste').toInsertableInlineContent
  const toRelativePath: typeof import('./lib/local-page-idmap').toRelativePath
  const toast: typeof import('./components/ui/sonner').toast
  const toggleSidebarFolder: typeof import('./stores/useSidebarView').toggleSidebarFolder
  const toggleVariants: typeof import('./components/ui/toggle').toggleVariants
  const transcodeVideo: typeof import('./lib/videoProcessor').transcodeVideo
  const triggerAutoWebdavBackup: typeof import('./lib/webdavSync').triggerAutoWebdavBackup
  const tryPasteGooseMarkdownFragment: typeof import('./components/editor/hooks/useEditorPaste').tryPasteGooseMarkdownFragment
  const uToolsStorage: typeof import('./lib/storage').uToolsStorage
  const updateQuickNoteSlotName: typeof import('./stores/useQuickNote').updateQuickNoteSlotName
  const updateSnapshotAfterWrite: typeof import('./lib/local-md-snapshot').updateSnapshotAfterWrite
  const updateSnapshotStat: typeof import('./lib/local-md-snapshot').updateSnapshotStat
  const uploadEditorFile: typeof import('./components/editor/utils/uploadEditorFile').uploadEditorFile
  const uploadWebdavBackup: typeof import('./lib/webdavSync').uploadWebdavBackup
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useAiStatus: typeof import('./stores/useAiStatus').useAiStatus
  const useAppHotkeys: typeof import('./hooks/useAppHotkeys').useAppHotkeys
  const useCallback: typeof import('react').useCallback
  const useCenteredActiveItemScroll: typeof import('./components/editor/hooks/useCenteredActiveItemScroll').useCenteredActiveItemScroll
  const useCompactViewport: typeof import('./hooks/useCompactViewport').useCompactViewport
  const useContext: typeof import('react').useContext
  const useContextMenu: typeof import('./components/editor/state/contextMenu').useContextMenu
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useDesktopHotkeys: typeof import('./hooks/useDesktopHotkeys').useDesktopHotkeys
  const useDesktopWindowTitleSync: typeof import('./hooks/useDesktopWindowTitle').useDesktopWindowTitleSync
  const useEditorFind: typeof import('./components/editor/hooks/useEditorFind').useEditorFind
  const useEditorPaste: typeof import('./components/editor/hooks/useEditorPaste').useEditorPaste
  const useEditorShortcuts: typeof import('./components/editor/hooks/useEditorShortcuts').useEditorShortcuts
  const useEditorSplit: typeof import('./stores/useEditorSplit').useEditorSplit
  const useEditorSplitSelector: typeof import('./stores/useEditorSplit').useEditorSplitSelector
  const useEditorUiScale: typeof import('./components/editor/hooks/useEditorUiScale').useEditorUiScale
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useEffectiveSingleTabMode: typeof import('./lib/tabMode').useEffectiveSingleTabMode
  const useFileNavHistory: typeof import('./stores/useFileNavHistory').useFileNavHistory
  const useFormatCode: typeof import('./components/editor/hooks/useFormatCode').useFormatCode
  const useFormattingToolbarAi: typeof import('./components/editor/state/formattingToolbarAi').useFormattingToolbarAi
  const useGlobalScrollActivity: typeof import('./components/editor/hooks/useGlobalScrollActivity').useGlobalScrollActivity
  const useHistoryRecorder: typeof import('./hooks/useHistoryRecorder').useHistoryRecorder
  const useHistoryView: typeof import('./stores/useHistoryView').useHistoryView
  const useId: typeof import('react').useId
  const useImeInput: typeof import('./hooks/useImeInput').useImeInput
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useLocalFolderTargetPicker: typeof import('./stores/useLocalFolderTargetPicker').useLocalFolderTargetPicker
  const useMemo: typeof import('react').useMemo
  const useMinHoldActive: typeof import('./components/ui/ai-motion').useMinHoldActive
  const useNativeContextMenuGuard: typeof import('./hooks/useNativeContextMenuGuard').useNativeContextMenuGuard
  const useNotebookAiChats: typeof import('./stores/useNotebookAiChats').useNotebookAiChats
  const useNotebooks: typeof import('./stores/useNotebooks').useNotebooks
  const useOptimistic: typeof import('react').useOptimistic
  const usePages: typeof import('./stores/pages/index').usePages
  const usePersistentDismissState: typeof import('./hooks/usePersistentDismissState').usePersistentDismissState
  const usePluginEvents: typeof import('./hooks/usePluginEvents').usePluginEvents
  const useQuickNote: typeof import('./stores/useQuickNote').useQuickNote
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useResolvedTheme: typeof import('./hooks/useResolvedTheme').useResolvedTheme
  const useSettings: typeof import('./stores/settings/index').useSettings
  const useSidebarView: typeof import('./stores/useSidebarView').useSidebarView
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTabs: typeof import('./stores/useTabs').useTabs
  const useTransition: typeof import('react').useTransition
  const useUToolsMcpBridge: typeof import('./hooks/useUToolsMcpBridge').useUToolsMcpBridge
  const useWindowAlwaysOnTop: typeof import('./hooks/useWindowAlwaysOnTop').useWindowAlwaysOnTop
  const validateGeneratedBlockStructure: typeof import('./lib/ai-write/index').validateGeneratedBlockStructure
  const videoStorage: typeof import('./lib/videoStorage').videoStorage
  const waitForFonts: typeof import('./lib/fontLoader').waitForFonts
  const wasRecentlyInteracting: typeof import('./lib/editor-interaction-signal').wasRecentlyInteracting
  const wasRecentlySelfWritten: typeof import('./lib/local-md-snapshot').wasRecentlySelfWritten
  const wikiKeysForLocalPath: typeof import('./lib/wikiLink').wikiKeysForLocalPath
  const wikiLinkDisplayTitle: typeof import('./lib/wikiLink').wikiLinkDisplayTitle
  const wikiPathKey: typeof import('./lib/wikiLink').wikiPathKey
  const withInternalPageTitle: typeof import('./components/editor/utils/page-title').withInternalPageTitle
  const writeDbStorageJSON: typeof import('./lib/storage').writeDbStorageJSON
  const writeLocalPageIdMap: typeof import('./lib/local-page-idmap').writeLocalPageIdMap
  const writePersistentDismissState: typeof import('./lib/dismiss-state').writePersistentDismissState
  const writeTabSplitForWindow: typeof import('./stores/useEditorSplit').writeTabSplitForWindow
}
// for type re-export
declare global {
  // @ts-ignore
  export type { ResolvedTheme } from './hooks/useResolvedTheme'
  import('./hooks/useResolvedTheme')
  // @ts-ignore
  export type { AiActivityPhase } from './stores/useAiStatus'
  import('./stores/useAiStatus')
  // @ts-ignore
  export type { EditorSplitStore } from './stores/useEditorSplit'
  import('./stores/useEditorSplit')
  // @ts-ignore
  export type { FileNavLocation } from './stores/useFileNavHistory'
  import('./stores/useFileNavHistory')
  // @ts-ignore
  export type { LocalFolderTargetPickerMode } from './stores/useLocalFolderTargetPicker'
  import('./stores/useLocalFolderTargetPicker')
  // @ts-ignore
  export type { NotebookAiConversation, NotebookAiNotebookChatState, NotebookAiChatsState } from './stores/useNotebookAiChats'
  import('./stores/useNotebookAiChats')
  // @ts-ignore
  export type { Notebook, LocalFolderLoadStatus, LocalFolderLoadState } from './stores/useNotebooks'
  import('./stores/useNotebooks')
  // @ts-ignore
  export type { QuickNoteSlot, QuickNoteDrafts, QuickNoteSlotNames } from './stores/useQuickNote'
  import('./stores/useQuickNote')
  // @ts-ignore
  export type { SettingsState, SearchProvider, Theme, AccentColor, CodeStyle, UToolsSettings, AISettings, DesktopHotkeyStatusState, DesktopHotkeyStatus, DesktopSettings, PrivacySettings, FontConfig, CustomFonts, CustomAction, UIFontSize } from './stores/settings/index'
  import('./stores/settings/index')
  // @ts-ignore
  export type { TabType, TabItem } from './stores/useTabs'
  import('./stores/useTabs')
  // @ts-ignore
  export type { AiBlockScopeKind, AiBlockScopeRange, AiBlockScope } from './lib/ai-block-scope'
  import('./lib/ai-block-scope')
  // @ts-ignore
  export type { CustomAIProtocol, AIProviderIdLike, AIModelOption, AIReasoningLevel, AISettingsLike, AIMessage, AIStreamPhase, AIStreamUpdate, AIRequestOverrides, RunAITextOptions, RunAITextStreamOptions, AIProviderId, AIProviderPreset } from './lib/ai-provider/index'
  import('./lib/ai-provider/index')
  // @ts-ignore
  export type { AiWriteAction, AiBlockRange, AiTargetMode, AiTargetSource, AiTargetSelection, AiTargetRef, AiStickyTarget, AiResolvedTarget, AiWritePlan, AiContextBundle, BlockTypeTransformIntent, BlockTypeTransformBlock, BlockTypeTransformPanelOpenDetail, BlockTypeTransformPlan, BlockTypeTransformResult, BlockTypeTransformSelectionSnapshot, BlockTypeTransformTarget, GeneratedBlockStructureExpectation, GeneratedBlockStructureValidationInput, GeneratedBlockStructureValidationResult, PseudoStructureMarkerIssue } from './lib/ai-write/index'
  import('./lib/ai-write/index')
  // @ts-ignore
  export type { DiskWriteError } from './lib/diskWriteError'
  import('./lib/diskWriteError')
  // @ts-ignore
  export type { FixedAppShortcutId } from './lib/fixed-app-shortcuts'
  import('./lib/fixed-app-shortcuts')
  // @ts-ignore
  export type { CardTheme, CardThemeId, NotebookCardThemeContext, WatermarkConfig } from './lib/imageExport/index'
  import('./lib/imageExport/index')
  // @ts-ignore
  export type { UnreferencedLocalAsset, RestoreMissingLocalAssetsResult } from './lib/local-folder-asset-maintenance'
  import('./lib/local-folder-asset-maintenance')
  // @ts-ignore
  export type { LocalFolderOpenAppKind, LocalFolderOpenAppCandidate } from './lib/local-folder-open-apps'
  import('./lib/local-folder-open-apps')
  // @ts-ignore
  export type { ParsedLocalMarkdown } from './lib/local-folder-scanner'
  import('./lib/local-folder-scanner')
  // @ts-ignore
  export type { LocalFolderTargetKey, LocalFolderPickerItem } from './lib/local-folder-target'
  import('./lib/local-folder-target')
  // @ts-ignore
  export type { LocalPageFrontmatterSettingsKey, LocalPageFrontmatterSettings, MergeFrontmatterResult } from './lib/local-frontmatter'
  import('./lib/local-frontmatter')
  // @ts-ignore
  export type { LocalMdFileStat } from './lib/local-md-snapshot'
  import('./lib/local-md-snapshot')
  // @ts-ignore
  export type { LocalPageIdMap } from './lib/local-page-idmap'
  import('./lib/local-page-idmap')
  // @ts-ignore
  export type { PageMentionNavigationResult } from './lib/pageMentionNavigation'
  import('./lib/pageMentionNavigation')
  // @ts-ignore
  export type { ModifierShortcut, MouseShortcut } from './lib/shortcut-match'
  import('./lib/shortcut-match')
  // @ts-ignore
  export type { PlatformKind } from './lib/utils'
  import('./lib/utils')
  // @ts-ignore
  export type { UToolsAdapter, SublistItem, UserInfo } from './lib/utools'
  import('./lib/utools')
  // @ts-ignore
  export type { VideoTranscodeProgress } from './lib/videoProcessor'
  import('./lib/videoProcessor')
  // @ts-ignore
  export type { WebdavBackupFile } from './lib/webdavSync'
  import('./lib/webdavSync')
  // @ts-ignore
  export type { ParsedWikiLink } from './lib/wikiLink'
  import('./lib/wikiLink')
  // @ts-ignore
  export type { LastNoteRestoreResult } from './lib/workspaceStartup'
  import('./lib/workspaceStartup')
  // @ts-ignore
  export type { BadgeProps } from './components/ui/badge'
  import('./components/ui/badge')
  // @ts-ignore
  export type { ButtonProps } from './components/ui/button'
  import('./components/ui/button')
  // @ts-ignore
  export type { DialogProps } from './components/ui/dialog'
  import('./components/ui/dialog')
  // @ts-ignore
  export type { IconButtonProps } from './components/ui/icon-button'
  import('./components/ui/icon-button')
  // @ts-ignore
  export type { ProgressProps } from './components/ui/progress'
  import('./components/ui/progress')
  // @ts-ignore
  export type { SelectableCardProps } from './components/ui/selectable-card'
  import('./components/ui/selectable-card')
  // @ts-ignore
  export type { BlockNoteContent, LegacyPageContent, PageContent } from './components/editor/utils/blocknote-content/index'
  import('./components/editor/utils/blocknote-content/index')
  // @ts-ignore
  export type { ToolbarRect, ToolbarPoint } from './components/editor/utils/formattingToolbarPosition'
  import('./components/editor/utils/formattingToolbarPosition')
  // @ts-ignore
  export type { ToolbarEdgeSide, ToolbarReferenceRect } from './components/editor/utils/formattingToolbarReference'
  import('./components/editor/utils/formattingToolbarReference')
  // @ts-ignore
  export type { ListPasteBlockType, InheritedPasteBlock, MultilinePastePlan, PasteContainerInspect } from './components/editor/utils/multilinePaste'
  import('./components/editor/utils/multilinePaste')
  // @ts-ignore
  export type { OpenExternalResourceResult } from './components/editor/utils/openResourceExternally'
  import('./components/editor/utils/openResourceExternally')
  // @ts-ignore
  export type { PasteAtCursorEditor } from './components/editor/utils/pasteAtCursor'
  import('./components/editor/utils/pasteAtCursor')
  // @ts-ignore
  export type { ClipboardImageSource } from './components/editor/utils/pasteClipboardImage'
  import('./components/editor/utils/pasteClipboardImage')
  // @ts-ignore
  export type { SlashMenuPagePolicy } from './components/editor/utils/slashMenuPolicy'
  import('./components/editor/utils/slashMenuPolicy')
  // @ts-ignore
  export type { SoftWrapInlineItem } from './components/editor/utils/softWrapPaste'
  import('./components/editor/utils/softWrapPaste')
  // @ts-ignore
  export type { EditorFileUploadDeps } from './components/editor/utils/uploadEditorFile'
  import('./components/editor/utils/uploadEditorFile')
  // @ts-ignore
  export type { EditorFindState } from './components/editor/hooks/useEditorFind'
  import('./components/editor/hooks/useEditorFind')
  // @ts-ignore
  export type { CachedPasteTarget } from './components/editor/hooks/useEditorPaste'
  import('./components/editor/hooks/useEditorPaste')
}
